# Netlify commands
[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/*"
  to = "/404"
  status = 200
